### ISSUE TITLE
Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'Wsl...'.

### ISSUE THREAD

**Issue by VojGin** [josStorer/RWKV-Runner#173]
I'm on Macbook Pro M1 Max and when I run wails dev or wails build. I get this.

I can also see that a few files get changed by the script

<img width="1512" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/5146396/ccff8eea-5baf-4eb2-9d15-035da63316ad">
<img width="1512" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/5146396/180aadec-022b-40aa-9ecb-450f480ac1e7">
<img width="1512" alt="image" src="https://github.com/josStorer/RWKV-Runner/assets/5146396/c190169a-fb95-450e-90ec-715be5e7bcd3">

`wails dev`

```zsh
Wails CLI v2.5.1

Executing: go mod tidy
  • Generating bindings:
Done.
  • Installing frontend dependencies:
Done.
  • Compiling frontend:

    > frontend@0.0.0 build
    > tsc && vite build

    src/pages/Train.tsx(10,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslCommand'.
    src/pages/Train.tsx(11,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslEnable'.
    src/pages/Train.tsx(12,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslInstallUbuntu'.
    src/pages/Train.tsx(13,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslIsEnabled'.
    src/pages/Train.tsx(14,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslStart'.
    src/pages/Train.tsx(15,3): error TS2305: Module '"../../wailsjs/go/backend_golang/App"' has no exported member 'WslStop'.
    src/pages/Train.tsx(333,16): error TS7006: Parameter 'e' implicitly has an 'any' type.
    src/pages/Train.tsx(348,14): error TS7006: Parameter 'e' implicitly has an 'any' type.
```

**Comment by VojGin** [comment]
The problem can be solved by replacing the `backend-golang/wsl.go` file with `backend-golang/wsl_not_windows.go`

**Comment by josStorer** [comment]
You can check the github workflow file to obtain detailed compilation scripts for various platforms:
https://github.com/josStorer/RWKV-Runner/blob/master/.github/workflows/release.yml#L138-L144

In order to execute WSL interaction, I've imported a package restricted to Windows only, you can't compile it directly on other platforms. Although I specified it using `//go:build`, Wails seems unable to generate JS bindings for it correctly. Therefore, I am currently compiling by manually replacing the file with the scripts above.
