### ISSUE TITLE
Trojan Warning from Windows Defender.

### ISSUE THREAD

**Issue by SoAp9035** [josStorer/RWKV-Runner#69]
I got a trojan warning from windows defender. 

I downloaded it today and used it for a few hours. When I opened it again, I got a trojan warning.

**Comment by josStorer** [comment]
My suggestion is to add it to the trusted list.
In order to avoid user downloading problems, I have embedded some Python scripts into the executable program and released them at runtime, which may be considered as virus behavior.
For security concerns about this program, firstly the code is completely open source, and the compilation process is also public, you can check it at https://github.com/josStorer/RWKV-Runner/blob/master/.github/workflows/release.yml

**Comment by hbj52152** [comment]
Hi, similar situation but faster.

Windows 11 did not give me the chance to add it to the trusted list.  .exe file deleted at the same moment as it was downloaded.

**Comment by TodayAI** [comment]
Install version 1.09:
https://github.com/josStorer/RWKV-Runner/releases/tag/v1.0.9

You can use this version without Windows defender warnings. It updates itself to the latest version.

**Comment by josStorer** [comment]
For anyone who has the same issue, try this: https://github.com/josStorer/RWKV-Runner/releases/download/v1.3.6/RWKV-Runner_win.zip

**Comment by Dobby233Liu** [comment]
> For anyone who has the same issue, try this: [`v1.3.7` RWKV-Runner_win.zip (download)](https://github.com/josStorer/RWKV-Runner/releases/download/v1.3.7/RWKV-Runner_win.zip)

WD thinks `RWKV-Runner.exe` is `Program:Win32/Contebrew.A!ml` after unzipping the file.. Database version is `1.393.638.0`

**Comment by josStorer** [comment]
@Dobby233Liu Add it to the trusted list or compile by yourself
